
services:
  astro-builder:
    build:
      context: .
      dockerfile: app-frontend/Dockerfile
    volumes:
      - shared-dist:/app/app-frontend/dist
    restart: no
    env_file: app-frontend/.env

  frontend-host:
    image: nginx:alpine
    volumes:
      - shared-dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - astro-builder
    restart: always

volumes:
  shared-dist:
