
services:

  astro-builder:
    build:
      context: .
      dockerfile: app-frontend/Dockerfile
    volumes:
      - static-dist:/app/app-frontend/dist
    depends_on:
      - mongo
    restart: no
    environment:
      - DATABASE_URI=mongodb://mongo:27017/payload
      - PAYLOAD_SECRET=SECRET-GOES-HERE
      - SITE_URL=https://localhost

  caddy:
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:2.10-alpine
        COPY Caddyfile /etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - static-dist:/srv:ro
      - caddy-data:/data
      - caddy-config:/config
    environment:
      - SITE_URL=localhost

  payload:
    build:
      context: .
      dockerfile: app-payload/Dockerfile
    depends_on:
      - mongo
    restart: always
    environment:
      - DATABASE_URI=mongodb://mongo:27017/payload
      - PAYLOAD_SECRET=SECRET-GOES-HERE
      - NEXT_PUBLIC_SERVER_URL=http://localhost
      - CRON_SECRET=YOUR_CRON_SECRET_HERE
      - PREVIEW_SECRET=YOUR_SECRET_HERE
      - SITE_URL=https://localhost

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - db-data:/data/db
    logging:
      driver: none

volumes:
  static-dist:
  db-data:
  caddy-data:
  caddy-config:
